name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  build-cad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make assets directory
        run: mkdir assets
      - name: Install OpenSCAD
        run: sudo apt-get install openscad
      - name: Build wheel parts
        run: |
          openscad -o assets/vessel.stl -D 'vessel();' src/cad/wheel.scad
          openscad -o assets/ring.stl -D 'ring();' src/cad/wheel.scad
          openscad -o assets/mold.stl -D 'mold();' src/cad/wheel.scad
          openscad -o assets/wheel.stl -D 'wheel();' src/cad/wheel.scad
      - name: Build frame
        run: |
          openscad -o assets/frame.stl src/cad/frame.scad
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: cad-assets
          path: assets

  build-bridge:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make assets directory
        run: mkdir assets
      - name: Run PyInstaller
        run: |
          cd src/bridge
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller bridge.spec
          cp dist/bridge.exe ../../assets
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: bridge-assets
          path: assets

  create-release:
    needs:
      - build-cad
      - build-bridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: assets
      - name: Copy stuff
        run: |
          cp src/bridge/buttplug-user-device-config.json assets
          cp src/firmware/firmware.ino assets
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Version ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
      - name: Upload release assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: assets
